language: objective-c

before_script:
   - gem install luffa --no-document --no-document --env-shebang --no-prerelease
   - gem install xcpretty --no-document --no-document --env-shebang --no-prerelease
   - luffa authorize

script:
  - script/ci/travis/build-and-stage-app.sh
  - script/ci/travis/bundle-install.rb
  - script/ci/travis/cucumber-ci.rb

notifications:
  email: false

