<%

xamarin_dir = "#{ENV['HOME']}/.xamarin"

devices = {}

device_list = ['neptune', 'venus', 'earp',
               'mars', 'saturn', 'pegasi',
               'hat', 'erik', 'denis']

device_list.each do |device|
  dir = "#{xamarin_dir}/devices/#{device}"
  ip = IO.read("#{dir}/ip") if File.exists?("#{dir}/ip")
  udid = IO.read("#{dir}/udid") if File.exists?("#{dir}/udid")
  devices[device.to_sym] = { dir: dir, ip: ip, udid: udid }
end

%>

common:  NO_STOP='1' -f Slowhandcuke::Formatter

### SIMULATOR ###

default: APP="./CalWebView-cal.app" -p common


### DEVICE ###
device_common: -p common BUNDLE_ID=com.xamarin.CalWebView-cal
hat:   DEVICE_TARGET=<%= devices[:hat][:udid] %> DEVICE_ENDPOINT=<%= devices[:hat][:ip] %> -p device_common
