<%

xamarin_dir = "#{ENV['HOME']}/.xamarin"

devices = {}

device_list = ['neptune', 'venus', 'earp',
               'mars', 'saturn', 'pegasi',
               'hat', 'erik', 'denis']

device_list.each do |device|
  dir = "#{xamarin_dir}/devices/#{device}"
  ip = IO.read("#{dir}/ip") if File.exists?("#{dir}/ip")
  udid = IO.read("#{dir}/udid") if File.exists?("#{dir}/udid")
  devices[device.to_sym] = { dir: dir, ip: ip, udid: udid }
end

if ENV["USER"] == "jenkins"
  formatter = "pretty"
else
  formatter = "Slowhandcuke::Formatter"
end

%>

common:  NO_STOP='1' -f <%= formatter %>

### SIMULATOR ###

default: APP="./Products/app-cal/CalWebView-cal.app" -p common

### DEVICE ###
device_common: -p common BUNDLE_ID=sh.calaba.CalWebView-cal
hat:   DEVICE_TARGET=<%= devices[:hat][:udid] %> DEVICE_ENDPOINT=<%= devices[:hat][:ip] %> -p device_common
pegasi:   DEVICE_TARGET=<%= devices[:pegasi][:udid] %> DEVICE_ENDPOINT=<%= devices[:pegasi][:ip] %> -p device_common
denis:   DEVICE_TARGET=<%= devices[:denis][:udid] %> DEVICE_ENDPOINT=<%= devices[:denis][:ip] %> -p device_common
neptune:   DEVICE_TARGET=<%= devices[:neptune][:udid] %> DEVICE_ENDPOINT=<%= devices[:neptune][:ip] %> -p device_common

